Added percentages
piecioshka/popularity-of-javascript-frameworks pull request #1
Opened 2018-07-23 12:22 UTC by ODudek

### Changelog: 
* Added method `sumValues` to get all value
* Added method `countPercent ` which count percent for every element of chart

2018-07-23 12:25 UTC, ODudek commented
Niepotrzebna pozostałość po funkcji, już ją wywalam ;)

2018-07-23 20:26 UTC, piecioshka commented on src/vendors/chart/setup-chart.js
> +    let sum = 0;
Proszę wykorzystać `Array.prototype.reduce`

2018-07-23 20:26 UTC, piecioshka commented on src/vendors/chart/setup-chart.js
> +function countPercent (value) {
Proszę usuń spację po nazwie funkcji

2018-07-23 20:27 UTC, piecioshka requested changes
Do weryfikacji

2018-07-23 21:03 UTC, piecioshka commented on src/vendors/chart/setup-chart.js
> +    return CHART_DATA.reduce((sum, nextElement) => sum += nextElement.value, 0)
Proszę zmień:
- `sum` na `mem`
- `nextElement` na `element`

Proszę abyś dopisać średnik na końcu.

Proszę niech ta funkcja będzie parametryzowana i niech przyjmie tablicą, które wartości doda.
Pewnie trzeba będzie wykonać Array.prototype.map aby wrzucić jej tylko wartości z klucza `value`

2018-07-23 21:04 UTC, piecioshka commented on src/vendors/chart/setup-chart.js
> +function countPercent(value) {
Funkcja `countPercent` wg zasady minimalnej odpowiedzialności (SRP) nie powinna nić wiedzieć o funkcji `sumValues`. Trzeba jakoś rozwiązać ten problem.

2018-07-23 21:04 UTC, piecioshka requested changes
Do weryfikacji.

Btw. Zrób `git rebase -i (squash)`, bo pierwsze rewizje masz z jakimś dziwnym mailem zrobione, bo się avatar nie wyświetla.

2019-09-01 18:42 UTC, merged

2019-09-01 18:42 UTC, piecioshka commented
Dziękuję @ODudek 🍺